// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by scripts/img-optimize.ts — do not edit by hand.
// Intrinsic dimensions + available responsive WebP variants for every site
// image. Consumed by src/lib/images.ts to add width/height (CLS = 0) and
// srcset/sizes (responsive delivery) to <img> elements.
// ─────────────────────────────────────────────────────────────────────────────

export type ImageEntry = { w: number; h: number; variants: number[] };

export const IMAGE_MANIFEST: Record<string, ImageEntry> = {
  "/logo-official.png": {
    "w": 1536,
    "h": 1536,
    "variants": [
      384,
      768
    ]
  },
  "/images/dest/agadir.jpg": {
    "w": 612,
    "h": 408,
    "variants": [
      480
    ]
  },
  "/images/dest/ait-ben-haddou.jpg": {
    "w": 620,
    "h": 407,
    "variants": [
      480
    ]
  },
  "/images/dest/akchour.jpg": {
    "w": 628,
    "h": 942,
    "variants": [
      480
    ]
  },
  "/images/dest/casablanca.jpg": {
    "w": 720,
    "h": 720,
    "variants": [
      480
    ]
  },
  "/images/dest/chefchaouen.jpg": {
    "w": 533,
    "h": 800,
    "variants": []
  },
  "/images/dest/dades-valley.jpg": {
    "w": 612,
    "h": 408,
    "variants": [
      480
    ]
  },
  "/images/dest/draa-valley.jpg": {
    "w": 612,
    "h": 406,
    "variants": [
      480
    ]
  },
  "/images/dest/el-jadida.jpg": {
    "w": 500,
    "h": 333,
    "variants": []
  },
  "/images/dest/erg-chebbi.jpg": {
    "w": 1024,
    "h": 683,
    "variants": [
      480
    ]
  },
  "/images/dest/essaouira.jpg": {
    "w": 1600,
    "h": 757,
    "variants": [
      480,
      960
    ]
  },
  "/images/dest/fes.jpg": {
    "w": 1200,
    "h": 800,
    "variants": [
      480
    ]
  },
  "/images/dest/ifrane.jpg": {
    "w": 1200,
    "h": 900,
    "variants": [
      480
    ]
  },
  "/images/dest/imlil.jpg": {
    "w": 1600,
    "h": 854,
    "variants": [
      480,
      960
    ]
  },
  "/images/dest/legzira.jpg": {
    "w": 675,
    "h": 900,
    "variants": [
      480
    ]
  },
  "/images/dest/marrakech.jpg": {
    "w": 612,
    "h": 406,
    "variants": [
      480
    ]
  },
  "/images/dest/meknes.jpg": {
    "w": 499,
    "h": 248,
    "variants": []
  },
  "/images/dest/merzouga.jpg": {
    "w": 1000,
    "h": 600,
    "variants": [
      480
    ]
  },
  "/images/dest/mirleft.jpg": {
    "w": 1200,
    "h": 800,
    "variants": [
      480
    ]
  },
  "/images/dest/nkob.jpg": {
    "w": 800,
    "h": 534,
    "variants": [
      480
    ]
  },
  "/images/dest/ouarzazate.jpg": {
    "w": 500,
    "h": 667,
    "variants": []
  },
  "/images/dest/ourika-valley.jpg": {
    "w": 1600,
    "h": 1195,
    "variants": [
      480,
      960
    ]
  },
  "/images/dest/ouzoud.jpg": {
    "w": 768,
    "h": 1024,
    "variants": [
      480
    ]
  },
  "/images/dest/rabat.jpg": {
    "w": 1600,
    "h": 1243,
    "variants": [
      480,
      960
    ]
  },
  "/images/dest/roses-valley.jpg": {
    "w": 612,
    "h": 381,
    "variants": [
      480
    ]
  },
  "/images/dest/skoura.jpg": {
    "w": 1024,
    "h": 567,
    "variants": [
      480
    ]
  },
  "/images/dest/taghazout.jpg": {
    "w": 940,
    "h": 560,
    "variants": [
      480
    ]
  },
  "/images/dest/tangier.jpg": {
    "w": 612,
    "h": 448,
    "variants": [
      480
    ]
  },
  "/images/dest/tetouan.jpg": {
    "w": 612,
    "h": 408,
    "variants": [
      480
    ]
  },
  "/images/dest/todra-gorge.jpg": {
    "w": 1024,
    "h": 683,
    "variants": [
      480
    ]
  },
  "/images/dest/zagora.jpg": {
    "w": 800,
    "h": 500,
    "variants": [
      480
    ]
  },
  "/images/food/couscous.jpg": {
    "w": 800,
    "h": 449,
    "variants": [
      480
    ]
  },
  "/images/food/pastries.jpg": {
    "w": 794,
    "h": 530,
    "variants": [
      480
    ]
  },
  "/images/food/streetfood.jpg": {
    "w": 1400,
    "h": 879,
    "variants": [
      480,
      960
    ]
  },
  "/images/food/tagine.jpg": {
    "w": 675,
    "h": 1200,
    "variants": [
      480
    ]
  },
  "/images/food/tea.jpg": {
    "w": 1000,
    "h": 1000,
    "variants": [
      480
    ]
  },
  "/images/guide/moha-amroui-desert-guide-camels-merzouga.jpg": {
    "w": 1440,
    "h": 1920,
    "variants": [
      480,
      960
    ]
  },
  "/images/hero/atlas-pano.jpg": {
    "w": 600,
    "h": 400,
    "variants": []
  },
  "/images/hero/desert-pano.jpg": {
    "w": 601,
    "h": 900,
    "variants": [
      480
    ]
  },
  "/images/hero/medina-pano.jpg": {
    "w": 794,
    "h": 712,
    "variants": [
      480
    ]
  },
  "/images/journeys/chefchaouen-blue-city-alley-morocco.jpg": {
    "w": 1066,
    "h": 1600,
    "variants": [
      480
    ]
  },
  "/images/journeys/fes-chouara-leather-tannery-morocco.jpg": {
    "w": 1067,
    "h": 1600,
    "variants": [
      480
    ]
  },
  "/images/journeys/moroccan-carved-wooden-door-medina-morocco.jpg": {
    "w": 1066,
    "h": 1600,
    "variants": [
      480
    ]
  },
  "/images/journeys/ouzoud-waterfalls-atlas-mountains-morocco.jpg": {
    "w": 1066,
    "h": 1600,
    "variants": [
      480
    ]
  },
  "/images/journeys/sahara-night-sky-stars-palm-trees-morocco.jpg": {
    "w": 1600,
    "h": 1275,
    "variants": [
      480,
      960
    ]
  },
  "/images/personal/dunes-camels-poster.jpg": {
    "w": 1200,
    "h": 2134,
    "variants": [
      480
    ]
  },
  "/images/personal/group-atlas.jpg": {
    "w": 1600,
    "h": 1200,
    "variants": [
      480,
      960
    ]
  },
  "/images/personal/guests-van.jpg": {
    "w": 1200,
    "h": 1600,
    "variants": [
      480
    ]
  },
  "/images/personal/guide-guest-tea-wide.jpg": {
    "w": 1600,
    "h": 1200,
    "variants": [
      480,
      960
    ]
  },
  "/images/personal/guide-guest-tea.jpg": {
    "w": 1600,
    "h": 1201,
    "variants": [
      480,
      960
    ]
  },
  "/images/personal/guide-portrait.jpg": {
    "w": 1086,
    "h": 1448,
    "variants": [
      480
    ]
  },
  "/images/personal/luxury-camp-dusk.jpg": {
    "w": 1254,
    "h": 1254,
    "variants": [
      480,
      960
    ]
  },
  "/images/personal/riad-tea.jpg": {
    "w": 1200,
    "h": 1800,
    "variants": [
      480
    ]
  },
  "/images/personal/sahara-dunes-golden.jpg": {
    "w": 1080,
    "h": 1350,
    "variants": [
      480
    ]
  },
  "/images/riad/bedroom.jpg": {
    "w": 1367,
    "h": 912,
    "variants": [
      480,
      960
    ]
  },
  "/images/riad/courtyard.jpg": {
    "w": 800,
    "h": 1198,
    "variants": [
      480
    ]
  },
  "/images/riad/rooftop.jpg": {
    "w": 1367,
    "h": 912,
    "variants": [
      480,
      960
    ]
  },
  "/images/stock/stargazing-merzouga.jpg": {
    "w": 1001,
    "h": 1500,
    "variants": [
      480
    ]
  },
  "/images/tours/3-day-sahara-marrakech.jpg": {
    "w": 683,
    "h": 1024,
    "variants": [
      480
    ]
  },
  "/images/tours/5-day-imperial-cities.jpg": {
    "w": 1600,
    "h": 893,
    "variants": [
      480,
      960
    ]
  },
  "/images/tours/7-day-grand-morocco.jpg": {
    "w": 1067,
    "h": 1600,
    "variants": [
      480
    ]
  },
  "/images/tours/family-morocco-adventure.jpg": {
    "w": 612,
    "h": 408,
    "variants": [
      480
    ]
  }
};
