// Localized About-page gap completions. These keys are intentionally kept in
// the gap layer so the generated locale files remain untouched.
export const aboutGaps = {
  fr: { about_scroll_hint:'Faites défiler pour en savoir plus', about_roots_heading:'Nos racines', about_roots_text:'Nous venons de Merzouga et chaque partie de notre travail est enracinée dans le Sahara où nous avons grandi.', about_promise_heading:'Notre promesse', about_promise_text:'Chaque circuit est accompagné par des personnes qui vivent ici, pas par une plateforme qui envoie un guide depuis ailleurs.', about_cta_sub:'Choisissez un itinéraire avec l’équipe qui connaît le mieux Merzouga.' },
  es: { about_scroll_hint:'Desplázate para saber más', about_roots_heading:'Nuestras raíces', about_roots_text:'Somos de Merzouga y cada parte de nuestro trabajo nace del Sáhara donde crecimos.', about_promise_heading:'Nuestra promesa', about_promise_text:'Cada tour está guiado por personas que viven aquí, no por una plataforma que envía un guía desde otro lugar.', about_cta_sub:'Elige un itinerario con el equipo que mejor conoce Merzouga.' },
  it: { about_scroll_hint:'Scorri per saperne di più', about_roots_heading:'Le nostre radici', about_roots_text:'Veniamo da Merzouga e ogni parte del nostro lavoro nasce dal Sahara in cui siamo cresciuti.', about_promise_heading:'La nostra promessa', about_promise_text:'Ogni tour è guidato da persone che vivono qui, non da una piattaforma che invia una guida da altrove.', about_cta_sub:'Scegli un itinerario con il team che conosce meglio Merzouga.' },
  de: { about_scroll_hint:'Scrollen, um mehr zu erfahren', about_roots_heading:'Unsere Wurzeln', about_roots_text:'Wir kommen aus Merzouga und unsere Arbeit ist fest in der Sahara verwurzelt, in der wir aufgewachsen sind.', about_promise_heading:'Unser Versprechen', about_promise_text:'Jede Reise wird von Menschen begleitet, die hier leben – nicht von einer Plattform, die einen Guide von anderswo schickt.', about_cta_sub:'Wählen Sie eine Route mit dem Team, das Merzouga am besten kennt.' },
  nl: { about_scroll_hint:'Scroll om meer te ontdekken', about_roots_heading:'Onze wortels', about_roots_text:'Wij komen uit Merzouga en ons werk is diep geworteld in de Sahara waar we zijn opgegroeid.', about_promise_heading:'Onze belofte', about_promise_text:'Elke rondreis wordt begeleid door mensen die hier wonen, niet door een platform dat een gids van elders stuurt.', about_cta_sub:'Kies een route met het team dat Merzouga het beste kent.' },
  pt: { about_scroll_hint:'Deslize para saber mais', about_roots_heading:'As nossas raízes', about_roots_text:'Somos de Merzouga e cada parte do nosso trabalho está enraizada no Saara onde crescemos.', about_promise_heading:'A nossa promessa', about_promise_text:'Cada viagem é guiada por pessoas que vivem aqui, não por uma plataforma que envia um guia de outro lugar.', about_cta_sub:'Escolha um itinerário com a equipa que melhor conhece Merzouga.' },
  zh: { about_scroll_hint:'向下了解更多', about_roots_heading:'我们的根', about_roots_text:'我们来自梅尔祖卡，我们的每一项工作都扎根于伴随我们成长的撒哈拉沙漠。', about_promise_heading:'我们的承诺', about_promise_text:'每一次旅行都由生活在这里的当地人带领，而不是由平台从其他地方派遣导游。', about_cta_sub:'与最了解梅尔祖卡的团队一起选择您的旅行路线。' },
  ja: { about_scroll_hint:'スクロールして詳しく見る', about_roots_heading:'私たちのルーツ', about_roots_text:'私たちはメルズーガ出身です。仕事のすべては、私たちが育ったサハラに根ざしています。', about_promise_heading:'私たちの約束', about_promise_text:'すべての旅を、ここに暮らす人々がご案内します。遠くからガイドを派遣する予約プラットフォームではありません。', about_cta_sub:'メルズーガを最もよく知るチームと旅程を選びましょう。' },
  ko: { about_scroll_hint:'스크롤하여 더 알아보기', about_roots_heading:'우리의 뿌리', about_roots_text:'우리는 메르주가에서 왔으며, 우리의 모든 일은 우리가 자란 사하라에 뿌리를 두고 있습니다.', about_promise_heading:'우리의 약속', about_promise_text:'모든 투어는 이곳에 사는 현지인이 안내합니다. 다른 곳에서 가이드를 보내는 예약 플랫폼이 아닙니다.', about_cta_sub:'메르주가를 가장 잘 아는 팀과 함께 여행 일정을 선택하세요.' },
  ar: { about_scroll_hint:'مرر للأسفل لمعرفة المزيد', about_roots_heading:'جذورنا', about_roots_text:'نحن من مرزوكة، وكل جزء من عملنا متجذر في الصحراء التي نشأنا فيها.', about_promise_heading:'وعدنا', about_promise_text:'كل جولة يقودها أشخاص يعيشون هنا، وليس منصة حجز ترسل دليلاً من مكان آخر.', about_cta_sub:'اختر رحلتك مع الفريق الذي يعرف مرزوكة أفضل من أي أحد.' },
} as const;
