// Spanish gap completions for route/hub and review UI.
export default {
  hub_by_departure_city:'Tours por ciudad de salida',hub_marrakech_name:'Marrakech',hub_fes_name:'Fez',hub_agadir_name:'Agadir',hub_casablanca_name:'Casablanca',
  hub_marrakech_title:'Tours desde Marrakech',hub_fes_title:'Tours desde Fez',hub_agadir_title:'Tours desde Agadir',hub_casablanca_title:'Tours desde Casablanca',
  hub_marrakech_hero_alt:'Marrakech, ciudad roja de Marruecos',hub_fes_hero_alt:'Medina de Fez, Marruecos',hub_agadir_hero_alt:'Costa atlántica de Agadir, Marruecos',hub_casablanca_hero_alt:'Mezquita Hassan II de Casablanca, Marruecos',
  hub_marrakech_intro:'Marrakech es uno de los principales puntos de partida para explorar Marruecos, desde el Alto Atlas hasta las kasbahs del sur y el Sahara.',hub_fes_intro:'Fez es el corazón cultural de Marruecos y un punto de partida natural hacia el Medio Atlas y la ruta a Merzouga.',hub_agadir_intro:'Agadir es una base atlántica para rutas hacia Essaouira, Marrakech, el sur de Marruecos y el Sahara.',hub_casablanca_intro:'Casablanca es un importante punto de llegada internacional y una base práctica para conectar las ciudades imperiales y el sur de Marruecos.',
  hub_marrakech_body:'Descubre los itinerarios realmente disponibles desde Marrakech y conecta la ciudad con las regiones del sur y las dunas de Erg Chebbi.',hub_fes_body:'Explora itinerarios privados desde Fez hacia el Medio Atlas, Merzouga y otros destinos de Marruecos.',hub_agadir_body:'Sal de Agadir para crear un viaje privado hacia el sur, el Sahara u otros destinos marroquíes.',hub_casablanca_body:'Sal de Casablanca para un itinerario privado por las ciudades imperiales, el sur o el Sahara.',
  hub_short_on_time:'Elige la duración del viaje',hub_short_on_time_sub:'Compara los formatos disponibles y elige el que mejor encaje con tu programa.',hub_browse_3day:'Descubre tours de 3 días desde {city}',hub_group_days_badge:'{days} días',hub_private_title:'Tours privados desde {city}',hub_private_sub:'Itinerarios y productos que existen realmente en los datos del viaje.',hub_explore_region:'Explora la región de {city}',hub_explore_region_sub:'Destinos relacionados con {city} para ayudarte a crear tu itinerario.',hub_custom_title:'¿Quieres un itinerario a medida desde {city}?',hub_custom_sub:'Indícanos fechas, intereses y ciudad de llegada y confirmaremos un itinerario privado.',
  hub_dur_crumb:'{days} días desde {city}',hub_dur_badge:'{days} días desde {city}',hub_dur_h1:'Tour de {days} días desde {city}',hub_dur_hero_alt:'Paisaje de Marruecos para un tour de {days} días desde {city}',hub_dur_intro_3:'Un formato de tres días desde {city}, con información transparente sobre el itinerario y la ruta.',hub_dur_intro_default:'Explora opciones de {days} días desde {city} y solicita la confirmación del itinerario antes de reservar.',hub_dur_body_3_day:'Los tours de tres días están pensados para aprovechar al máximo el tiempo disponible. Cuando la ruta lo permite, puedes conectar {ait} y {erg}.',hub_dest_erg_chebbi:'Erg Chebbi',hub_dest_ait_ben_haddou:'Aït Ben Haddou',hub_dur_dept_title:'Tours de {days} días con salida desde {city}',hub_dur_dept_sub:'Aquí solo aparecen tours de la duración solicitada presentes en los datos del proyecto.',hub_dur_none_title:'No hay un tour fijo de {days} días desde {city}',hub_dur_none_body:'No se publica un producto fijo verificado para esta combinación. Puedes solicitar un itinerario privado y recibir confirmación antes de pagar.',hub_dur_other:'Otras opciones desde {city}',hub_dur_highlights:'Destinos relacionados',hub_dur_faq_heading:'Preguntas sobre tours de {days} días desde {city}',hub_dur_faq_more:'¿Tienes más preguntas?',hub_dur_faq_link:'Ver todas las preguntas frecuentes',hub_dur_faq_questions:'O escríbenos por WhatsApp',hub_dur_wa:'WhatsApp',hub_dur_cta_title:'¿Listo para planificar {days} días desde {city}?',hub_dur_cta_sub:'Confirmaremos la ruta, las inclusiones y las condiciones antes de reservar.',hub_dur_3:'Tours de 3 días',hub_dur_4:'Tours de 4 días',hub_dur_5_6:'Tours de 5–6 días',hub_dur_7_8:'Tours de 7–8 días',hub_dur_9:'Tours de 9+ días',hub_dur_daytrips:'Excursiones y escapadas cortas',
  reviews_about_mohamed:'Lo que dicen los viajeros sobre Mohamed',reviews_google:'Reseñas de Google',review_read_google:'Leer en Google',review_source:'Fuente',about_book_cta:'Reservar ahora'
} as Record<string,string>;
